runtime: python39

instance_class: B4_1G
basic_scaling: 
  max_instances: 25
  # idle_timeout: 5m

service: service-7 # changed

vpc_access_connector:
 name: projects/finance-for-women-3/locations/europe-west1/connectors/connector-1

env_variables:
  OPENAI_API_KEY: "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"

# resources:
#   memory_gb: 6.5
#   disk_size_gb: 20