# APP ENGINE
runtime: python39

instance_class: B4_1G
basic_scaling: 
  max_instances: 25
  # idle_timeout: 5m

service: # insert service name

vpc_access_connector:
 name: # insert VPC connector name

env_variables:
  OPENAI_API_KEY: # insert API key

# resources:
#   memory_gb: 6.5
#   disk_size_gb: 20